-- RedefineTables
PRAGMA defer_foreign_keys=ON;
PRAGMA foreign_keys=OFF;
CREATE TABLE "new_Registration" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "firstName" TEXT NOT NULL,
    "lastName" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "registrationType" TEXT NOT NULL,
    "address1" TEXT NOT NULL,
    "address2" TEXT,
    "country" TEXT NOT NULL,
    "city" TEXT NOT NULL,
    "state" TEXT NOT NULL,
    "zipCode" TEXT NOT NULL,
    "gender" TEXT,
    "genderOther" TEXT,
    "region" TEXT,
    "certificateOfAttendance" BOOLEAN NOT NULL DEFAULT false,
    "vatRequired" BOOLEAN NOT NULL DEFAULT false,
    "vatNumber" TEXT,
    "studentProofFileName" TEXT,
    "hasDisability" TEXT,
    "disabilitySpecify" TEXT,
    "disabilityDetail" TEXT,
    "dietaryRestrictions" TEXT,
    "cvOptIn" TEXT,
    "cvFileName" TEXT,
    "visaSupportLetter" TEXT,
    "postalMailOptOut" BOOLEAN NOT NULL DEFAULT false,
    "emailOptOut" TEXT,
    "virtualConsent" BOOLEAN NOT NULL DEFAULT false,
    "ukEea" TEXT,
    "ukEeaConsent" TEXT,
    "acmDisabilityDetails" TEXT,
    "genderIdentity" TEXT,
    "birthYear" TEXT,
    "ethnicOrigin" TEXT,
    "ethnicOriginDetails" TEXT,
    "race" TEXT,
    "raceDetails" TEXT,
    "acmDisability" TEXT,
    "currentCountry" TEXT,
    "mainItem" TEXT,
    "banquet" TEXT,
    "mentoringSymposium" TEXT,
    "paperAuthor" TEXT,
    "fseTrack" TEXT,
    "paperId" TEXT,
    "reroutedPresentations" TEXT,
    "paperTitle" TEXT,
    "paperAuthors" TEXT,
    "paperOriginalUrl" TEXT,
    "addOns" TEXT,
    "oneDayEvent" TEXT,
    "coLocatedConference" TEXT,
    "totalAmount" REAL NOT NULL DEFAULT 0
);
INSERT INTO "new_Registration" ("acmDisability", "addOns", "address1", "address2", "banquet", "birthYear", "certificateOfAttendance", "city", "coLocatedConference", "country", "createdAt", "currentCountry", "cvFileName", "cvOptIn", "dietaryRestrictions", "email", "emailOptOut", "ethnicOrigin", "ethnicOriginDetails", "firstName", "gender", "genderIdentity", "genderOther", "hasDisability", "id", "lastName", "mainItem", "mentoringSymposium", "oneDayEvent", "paperAuthor", "postalMailOptOut", "race", "raceDetails", "region", "registrationType", "reroutedPresentations", "state", "studentProofFileName", "totalAmount", "ukEea", "vatNumber", "virtualConsent", "visaSupportLetter", "zipCode") SELECT "acmDisability", "addOns", "address1", "address2", "banquet", "birthYear", "certificateOfAttendance", "city", "coLocatedConference", "country", "createdAt", "currentCountry", "cvFileName", "cvOptIn", "dietaryRestrictions", "email", "emailOptOut", "ethnicOrigin", "ethnicOriginDetails", "firstName", "gender", "genderIdentity", "genderOther", "hasDisability", "id", "lastName", "mainItem", "mentoringSymposium", "oneDayEvent", "paperAuthor", "postalMailOptOut", "race", "raceDetails", "region", "registrationType", "reroutedPresentations", "state", "studentProofFileName", "totalAmount", "ukEea", "vatNumber", "virtualConsent", "visaSupportLetter", "zipCode" FROM "Registration";
DROP TABLE "Registration";
ALTER TABLE "new_Registration" RENAME TO "Registration";
PRAGMA foreign_keys=ON;
PRAGMA defer_foreign_keys=OFF;
