-- CreateTable
CREATE TABLE "Registration" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "firstName" TEXT NOT NULL,
    "lastName" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "registrationType" TEXT NOT NULL,
    "address1" TEXT NOT NULL,
    "address2" TEXT,
    "country" TEXT NOT NULL,
    "city" TEXT NOT NULL,
    "state" TEXT NOT NULL,
    "zipCode" TEXT NOT NULL,
    "gender" TEXT,
    "genderOther" TEXT,
    "region" TEXT,
    "certificateOfAttendance" BOOLEAN NOT NULL DEFAULT false,
    "vatNumber" TEXT,
    "studentProofFileName" TEXT,
    "hasDisability" TEXT,
    "dietaryRestrictions" TEXT,
    "cvOptIn" TEXT,
    "cvFileName" TEXT,
    "visaSupportLetter" TEXT,
    "postalMailOptOut" BOOLEAN NOT NULL DEFAULT false,
    "emailOptOut" TEXT,
    "virtualConsent" BOOLEAN NOT NULL DEFAULT false,
    "ukEea" TEXT,
    "genderIdentity" TEXT,
    "birthYear" TEXT,
    "ethnicOrigin" TEXT,
    "ethnicOriginDetails" TEXT,
    "race" TEXT,
    "raceDetails" TEXT,
    "acmDisability" TEXT,
    "currentCountry" TEXT,
    "mainItem" TEXT,
    "banquet" TEXT,
    "mentoringSymposium" TEXT,
    "paperAuthor" TEXT,
    "reroutedPresentations" TEXT,
    "addOns" TEXT,
    "oneDayEvent" TEXT,
    "coLocatedConference" TEXT,
    "totalAmount" REAL NOT NULL DEFAULT 0
);
